apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: todo-postgresql
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Caseraw/OpenShift-ShowTime.git
      ref: main
    contextDir: components/2-tier-todo-app/src/postgresql
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: todo-postgresql:latest
  triggers:
    - type: ConfigChange
