apiVersion: v1
kind: Service
metadata:
  name: todo-postgresql
  labels:
    app: todo-postgresql
spec:
  selector:
    app: todo-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
