apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-postgresql
  labels:
    app.kubernetes.io/name: todo-postgresql
    app.kubernetes.io/part-of: 2-tier-todo-app
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: todo-postgresql
  project: default
  source:
    path: components/2-tier-todo-app/kustomize/postgresql
    repoURL: 'https://github.com/Caseraw/OpenShift-ShowTime.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
